import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createTinyPack } from './helpers.js';
import { publish, verifyPack } from '../../src/pack/publish/index.js';

// D-001 part 2: verify-pack must fail if the on-disk package contains files
// that the freeze-receipt did not fingerprint and that aren't in the
// publish-generated allowlist. Without this check, a stale-artifact leak
// from a prior publish run survives silently.

let outerTmp: string;

beforeEach(() => {
  outerTmp = mkdtempSync(join(tmpdir(), 'ros-test-orphan-'));
});

afterEach(() => {
  rmSync(outerTmp, { recursive: true, force: true });
});

describe('verifyPack — orphan-artifact detection', () => {
  it('FAILS when an unexpected file is present in pack/', async () => {
    const packDir = join(outerTmp, 'source');
    const pkgDir = join(outerTmp, 'packages/test-package');
    mkdirSync(packDir, { recursive: true });

    createTinyPack(packDir);
    await publish({ fromDir: packDir, toDir: pkgDir });

    // Drop an orphan file into the published package under pack/ — that's
    // the location an operator could accidentally leave a stale artifact.
    const orphanPath = join(pkgDir, 'pack/sections/01-test/ORPHAN.txt');
    writeFileSync(orphanPath, 'orphan content', 'utf8');

    const result = verifyPack(pkgDir);
    expect(result.pass).toBe(false);
    expect(result.reason ?? '').toMatch(/Orphan artifact/);
    expect(result.reason ?? '').toContain('ORPHAN.txt');
  });

  it('FAILS when an unexpected file is present at the package root', async () => {
    const packDir = join(outerTmp, 'source');
    const pkgDir = join(outerTmp, 'packages/test-package');
    mkdirSync(packDir, { recursive: true });

    createTinyPack(packDir);
    await publish({ fromDir: packDir, toDir: pkgDir });

    // Drop a top-level orphan (e.g. a stale auxiliary file from a prior run).
    writeFileSync(join(pkgDir, 'leftover.txt'), 'should not be here', 'utf8');

    const result = verifyPack(pkgDir);
    expect(result.pass).toBe(false);
    expect(result.reason ?? '').toMatch(/Orphan artifact/);
    expect(result.reason ?? '').toContain('leftover.txt');
  });

  it('PASSES when only fingerprinted and publish-generated files are present', async () => {
    const packDir = join(outerTmp, 'source');
    const pkgDir = join(outerTmp, 'packages/test-package');
    mkdirSync(packDir, { recursive: true });

    createTinyPack(packDir);
    const result = await publish({ fromDir: packDir, toDir: pkgDir });

    // A clean publish must verify cleanly — every file is either
    // fingerprinted by freeze or generated by publish.
    expect(result.verifyPassed).toBe(true);
  });

  it('does not flag docs/how-to-read-this.md as orphan', async () => {
    const packDir = join(outerTmp, 'source');
    const pkgDir = join(outerTmp, 'packages/test-package');
    mkdirSync(packDir, { recursive: true });

    createTinyPack(packDir);
    await publish({ fromDir: packDir, toDir: pkgDir });

    // The scaffold lives at docs/how-to-read-this.md — it's generated by
    // publish, not fingerprinted by freeze. Must not be flagged.
    const result = verifyPack(pkgDir);
    expect(result.pass).toBe(true);
  });
});
